#!/usr/sbin/nft -f
# TRUST-NG firewall: hanya klien terdaftar (set client dari /etc/client_set)
# yang boleh query DNS :53. Sisanya silent-drop (resolver tak terlihat).

flush ruleset

table ip filter {
        set client {
                typeof ip saddr
                flags interval
                auto-merge
                include "/etc/client_set"
        }
        chain input {
                type filter hook prerouting priority filter; policy accept;
                ip saddr @client return
                udp dport { 53 } drop
                tcp dport { 53 } drop
        }
}

table ip6 filter {
        set client {
                typeof ip6 saddr
                flags interval
                auto-merge
                include "/etc/client6_set"
        }
        chain input {
                type filter hook prerouting priority filter; policy accept;
                ip6 saddr @client return
                udp dport { 53 } drop
                tcp dport { 53 } drop
        }
}
