[Service]
Type=simple
ExecStartPre=
ExecStart=
ExecStartPre=-/usr/local/sbin/unbound-anchor -a /var/lib/unbound/root.key
ExecStart=/usr/local/sbin/unbound -d -c /etc/unbound/unbound.conf
SupplementaryGroups=unbound
